NCLUDE_DIRS = 
LIB_DIRS = 

CDEFS= 
CFLAGS= -O3 -g $(INCLUDE_DIRS) $(CDEFS)
LIBS= -lpthread -lrt

PRODUCT=vxtolinux

HFILES=
CFILES= vxtolinux.c

SRCS= ${HFILES} ${CFILES}
OBJS= ${CFILES:.c=.o}

all:	${PRODUCT}

clean:
	-rm -f *.o *.NEW *~ *.d
	-rm -f ${PRODUCT} ${GARBAGE}

vxtolinux:	vxtolinux.o
	$(CC) $(LDFLAGS) $(CFLAGS) -o $@ vxtolinux.o $(LIBS)

depend:

.c.o:
	$(CC) -MD $(CFLAGS) -c $<
